bump_version: null
lint:
  files_exist:
    - .github/workflows/branch.yml
    - .github/workflows/ci.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - conf/igenomes.config
    - .editorconfig
    - .prettierignore
    - .prettierrc.yml
    - CITATIONS.md
    - assets/multiqc_config.yml
    - CHANGELOG.md
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - conf/test.config
    - conf/test_full.config
    - .github/workflows/ci.yml
    - .github/workflows/branch.yml
    - .github/workflows/ci.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - .editorconfig
    - .prettierignore
    - .prettierrc.yml
    - CITATIONS.md
    - assets/multiqc_config.yml
    - CHANGELOG.md
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - conf/test.config
    - conf/test_full.config
    - .github/workflows/ci.yml
    - CODE_OF_CONDUCT.md
    - assets/nf-core-vocseq_logo_light.png
    - docs/images/nf-core-vocseq_logo_light.png
    - docs/images/nf-core-vocseq_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/CONTRIBUTING.md
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - CODE_OF_CONDUCT.md
    - assets/nf-core-vocseq_logo_light.png
    - docs/images/nf-core-vocseq_logo_light.png
    - docs/images/nf-core-vocseq_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
  included_configs: false
  multiqc_config: false
  nextflow_config: false
  readme:
    - nextflow_badge
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Manjot Hunjan
  description:
    A pipeline for processing wastewater sequencing data to identify and
    quantify Variants of Concern, including trimming, alignment, clade definition,
    and abundance estimation.
  force: true
  is_nfcore: false
  name: vocseq
  org: alvoc
  outdir: .
  skip_features:
    - ci
    - igenomes
    - github_badges
    - nf_core_configs
    - code_linters
    - citations
    - gitpod
    - codespaces
    - multiqc
    - fastqc
    - changelog
    - email
    - adaptivecard
    - slackreport
    - test_config
    - seqera_platform
  version: 0.1.0
update: null
